spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/factory
    username: root
    password: 123456
    name: jdbc/factoryj


server:
  port: 8080

  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /test

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  #可选 mapper.xml中返回类型可以只写类名，不写包名
  type-aliases-package: com.daydream.javaee.pojo